// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDPc4edqMltDhQAaci1GEREb_co1jg8Qg',
    appId: '1:441708942878:web:1954c1082b0310b345c00f',
    messagingSenderId: '441708942878',
    projectId: 'lingobytes-e63fc',
    authDomain: 'lingobytes-e63fc.firebaseapp.com',
    storageBucket: 'lingobytes-e63fc.appspot.com',
    measurementId: 'G-RNC4LBBYYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVXIAPPG7egCe4A8qvYC1BGrkLGCU8g3A',
    appId: '1:441708942878:android:01750750f66177cd45c00f',
    messagingSenderId: '441708942878',
    projectId: 'lingobytes-e63fc',
    storageBucket: 'lingobytes-e63fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXzCvksi33kK4wsftXgoxwR17kyBedckU',
    appId: '1:441708942878:ios:f20fed3c95b8c57145c00f',
    messagingSenderId: '441708942878',
    projectId: 'lingobytes-e63fc',
    storageBucket: 'lingobytes-e63fc.appspot.com',
    iosBundleId: 'com.example.lingobytesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXzCvksi33kK4wsftXgoxwR17kyBedckU',
    appId: '1:441708942878:ios:f20fed3c95b8c57145c00f',
    messagingSenderId: '441708942878',
    projectId: 'lingobytes-e63fc',
    storageBucket: 'lingobytes-e63fc.appspot.com',
    iosBundleId: 'com.example.lingobytesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDPc4edqMltDhQAaci1GEREb_co1jg8Qg',
    appId: '1:441708942878:web:bbdaaeabfb4cc4bc45c00f',
    messagingSenderId: '441708942878',
    projectId: 'lingobytes-e63fc',
    authDomain: 'lingobytes-e63fc.firebaseapp.com',
    storageBucket: 'lingobytes-e63fc.appspot.com',
    measurementId: 'G-F32RPERVRY',
  );
}
